Documentation:
  - docs/*
  - docs/**/*
  - ./*.rst
  - ./*.md
  - LICENSE
  - .readthedocs.yml

Python:
  - brainstat/*
  - brainstat/**/*
  - setup.py
  - requirements.txt

MATLAB:
  - brainstat_matlab/*
  - brainstat_matlab/**/*

Github:
  - .github/*
  - .github/**/*
