name: "development_release"

on:
  push:
    branches:
      - development

jobs:
  development-release:
    name: "Development Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8.
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Python BrainStat.
      run: |
        python -m pip install --upgrade pip
        python -m pip install build --user
    
    - name: Build binary wheel and tarball.
      run: |
        python -m build --sdist --wheel --outdir dist/

    - name: Publish to PyPi test.
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
